/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-12-07 22:54:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.hoadonbean;
import Bo.hoadonbo;
import Bo.loaibo;
import Bo.Giohang;
import bean.giohangbean;
import Bo.Giohang;
import Bo.sachbo;
import Bo.loaibo;
import java.util.ArrayList;
import bean.sachbean;
import dao.sachdao;
import bean.loaibean;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.time.LocalDate;

public final class Lichsumuahang_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.sachdao");
    _jspx_imports_classes.add("Bo.loaibo");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("Bo.sachbo");
    _jspx_imports_classes.add("bean.hoadonbean");
    _jspx_imports_classes.add("bean.giohangbean");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("Bo.hoadonbo");
    _jspx_imports_classes.add("bean.loaibean");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("Bo.Giohang");
    _jspx_imports_classes.add("bean.sachbean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("<nav class=\"navbar navbar-inverse\" style=\"width:1300px;width:100%;margin:0; color: #fff ; background-color: #02225D; opacity: 0.9;top:0;'\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">SÁCH ONLINE</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav \">\r\n");
      out.write("     \r\n");
      out.write("      <li><a href=\"htsach\">Trang Chủ</a></li>\r\n");
      out.write("      <li>\r\n");
      out.write("      <a href=\"dathang\">Giỏ Hàng</a>\r\n");
      out.write("      <i class=\"fa-solid fa-cart-shopping search__cart\"></i>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("       <div valign=\"top\" style=\"display:inline-block;  text-align:center;\">\r\n");
      out.write("       \r\n");
      out.write("	<form action=\"htsach.jsp\" method=\"post\" style=\"display:inline-flex; margin-top: 5px;\">\r\n");
      out.write("      <input style=\"color: black;padding:8px 700px 8px 8px; name=\"txttk\" type=\"text\" value=\"\" placeholder=\"Tìm Kiếm\"> <br>\r\n");
      out.write("      <input style=\"height: 43px;\"  class=\"btn btn-warning \"name=\"buttim\" type=\"submit\" value=\"Tim\">\r\n");
      out.write("   	</form>\r\n");
      out.write("   	\r\n");
      out.write("		</div>\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("      \r\n");
      out.write("      ");
if( session.getAttribute("dn")==null)
      	{
      out.write("\r\n");
      out.write("      	<li><a href=\"dangky\"><span class=\"glyphicon glyphicon-user\"></span> Đăng Ký</a></li> \r\n");
      out.write("      <li><a href=\"ktdn\"><span class=\"glyphicon glyphicon-log-in\"></span> Đăng Nhập</a></li>\r\n");
      out.write("    		");
}else {
      out.write("\r\n");
      out.write("    			 <li><a href=\"ktdn\" ");
 request.setAttribute("lg", "o"); 
      out.write("><span class=\"glyphicon glyphicon-log-in\"></span> Đăng Xuất</a></li>\r\n");
      out.write("    			<li><a href=\"#\"><span class=\"glyphicon glyphicon-log-in\"></span> hi ");
      out.print( session.getAttribute("dn") );
      out.write("</a></li> \r\n");
      out.write("    			\r\n");
      out.write("    		");
} 
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write(" <table class=\"table giohang\" style=\"    margin: 0 25% 0 25%;    display: list-item;\" >\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th style=\"text-align: center;\"	>Thời gian thanh toán</th>\r\n");
      out.write("								<th style=\"text-align: center;\">Số Tiền thanh toán</th>\r\n");
      out.write("								<th style=\"text-align: center;\">Số Lượng Sách đã mua</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("			     ");
 ArrayList<hoadonbean> listhd = (ArrayList<hoadonbean>) request.getAttribute("listhd");
				   	for(hoadonbean aa: listhd){
      out.write("  \r\n");
      out.write("				   		     <tr>\r\n");
      out.write("					   			 <td style=\"text-align: center;\">");
      out.print(aa.getNgaythanhtoan().toString());
      out.write("</td>\r\n");
      out.write("						   		 <td style=\"text-align: center;\">");
      out.print(aa.getSotien());
      out.write("</td>\r\n");
      out.write("						   		 <td style=\"text-align: center;\">");
      out.print(aa.getsize());
      out.write("</td>\r\n");
      out.write("						   		 <td><a href=\"Xemchitiet?ngay=");
      out.print(aa.getNgaythanhtoan().toString());
      out.write("\">Xem Chi Tiết</a></td>\r\n");
      out.write("					   		 </tr>\r\n");
      out.write("					   	");
} 
      out.write("\r\n");
      out.write("					 \r\n");
      out.write("</table>\r\n");
if( request.getAttribute("dssachmua")!=null ){ 
      out.write("\r\n");
      out.write(" <table class=\"table giohang\" style=\" margin: 100px 25% 0 25%;    display: list-item;\" >\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th style=\"text-align: center;\"	>Mã sách</th>\r\n");
      out.write("								<th style=\"text-align: center;\">Hình Ảnh</th>\r\n");
      out.write("								<th style=\"text-align: center;\">Tên sách</th>\r\n");
      out.write("								<th style=\"text-align: center;\"	>Giá cả</th>\r\n");
      out.write("								<th style=\"text-align: center;\">Số lượng mua</th>\r\n");
      out.write("								<th style=\"text-align: center;\">Thành tiền</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("			     ");
 
			     	ArrayList<giohangbean> listsach = (ArrayList<giohangbean>) request.getAttribute("dssachmua");
			     	for(giohangbean a: listsach){
      out.write("  \r\n");
      out.write("				   		     <tr>\r\n");
      out.write("						   		 <td style=\"text-align: center;\">");
      out.print(a.getMasach());
      out.write("</td>\r\n");
      out.write("					   			 <td style=\"text-align: center;\"><img width = \"100px\" src=\"");
      out.print(a.getAnh());
      out.write("\"></td>\r\n");
      out.write("						   		 <td style=\"text-align: center;\">");
      out.print(a.getTensach());
      out.write("</td>\r\n");
      out.write("						   		 <td style=\"text-align: center;\">");
      out.print(a.getGia());
      out.write("</td>\r\n");
      out.write("						   		 <td style=\"text-align: center;\">");
      out.print(a.getSoluong());
      out.write("</td>\r\n");
      out.write("						   		 <td style=\"text-align: center;\">");
      out.print(a.getThanhtien());
      out.write("</td>\r\n");
      out.write("					   		 </tr>\r\n");
      out.write("					   	");
} 
      out.write("\r\n");
      out.write("					    	");
} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
